Add email validator
Nullify-Platform/config-file-parser pull request #10
Opened 2023-03-24 04:13 UTC by yushindkang

## Description

Add email validator for secrets push workflow

## Linked issues

[- (issue)](https://github.com/Nullify-Platform/Rebel-Base/issues/90)

## Checklist

- [ ] I have added one of the `patch`, `minor`, `major` or `no-release` labels
- [ ] I have performed a self-review of my own code
- [ ] I have checked for redundant or commented out code
- [ ] I have commented my code where I can't make it self-documenting
- [ ] I have made corresponding changes to the documentation
- [ ] I have added any appropriate tests

2023-03-24 05:24 UTC, yushindkang commented on cmd/main.go
> +	fmt.Println("ignore dirs:")
@dstrates

2023-03-25 01:01 UTC, tim-thacker-nullify requested changes

2023-03-25 01:01 UTC, tim-thacker-nullify commented on pkg/validator/emails_test.go
> +			fmt.Printf("testing config: %v\n", scenario.config.EmailNotifications)
I dont think we need this printf, we only want console output if this test fails which is handled by the assert below

2023-03-25 01:01 UTC, tim-thacker-nullify commented on pkg/validator/emails_test.go
> +const configStr1 string = `
I think we should have more descriptive variable names for all of these

2023-03-28 02:10 UTC, yushindkang commented on pkg/validator/emails.go
> +	}
@tim-thacker-nullify but if they have something like 
`
email_notifications: []
`
shouldn't this be valid? They might not choose to have any emails. We should only return invalid if the email format is incorrect no?

2023-03-28 02:28 UTC, tim-thacker-nullify commented on pkg/validator/emails.go
> +	}
`[]` is different to `[""]`, the latter is length 1 instead of 0 and has an empty string in it. an empty string isnt a valid email.

2023-03-28 07:31 UTC, tim-thacker-nullify requested changes

2023-03-28 07:31 UTC, tim-thacker-nullify commented on pkg/validator/emails.go
> +	}
maybe we can filter out empty strings first

2023-03-29 05:41 UTC, yushindkang commented on pkg/validator/emails_test.go
> +		{
@tim-thacker-nullify the config will never be nil because we set a default config with NewDefaultConfig() in the force. And the minimumcommentseverity test fails with `config: nil` as well because of nil pointer errors

2023-03-29 05:41 UTC, yushindkang commented on pkg/validator/emails.go
> +	}
@tim-thacker-nullify fixed

2023-03-29 06:13 UTC, tim-thacker-nullify commented on pkg/validator/emails_test.go
> +		{
fair

2023-03-29 06:15 UTC, tim-thacker-nullify commented on pkg/validator/emails.go
> +	}
isnt this checked by the loop below?

2023-03-29 23:14 UTC, yushindkang commented on pkg/validator/emails.go
> +	}
@tim-thacker-nullify yup it is. Removed

2023-04-04 23:14 UTC, tim-thacker-nullify approved these changes

2023-04-04 23:14 UTC, merged