Add TicketCreation and Jira options
Nullify-Platform/config-file-parser pull request #107
Opened 2024-05-01 09:44 UTC by jonathanlam

## Description

- Add Jira project key and issue type for automatic ticket creation upon findings

## Checklist

- [x] I have added one of the `patch`, `minor`, `major` or `no-release` labels
- [ ] I have linked an issue from this repository using the **Development** option
- [ ] I have performed a self-review of my own code
- [x] I have checked for redundant or commented out code
- [x] I have commented my code where I can't make it self-documenting
- [ ] I have made corresponding changes to the documentation
- [ ] I have added any appropriate tests

2024-05-01 13:21 UTC, tim-thacker-nullify requested changes

2024-05-01 13:21 UTC, tim-thacker-nullify commented on examples/nullify.yaml
> +ticket_creation:
should we call this project_platform instead?

2024-05-01 13:21 UTC, tim-thacker-nullify commented on pkg/models/tickets.go
> +	Jira    Jira `yaml:"jira,omitempty"`
i think this makes more sense since we default to github issues.
theres no need for an enabled field, just specify jira if you want it to start being created there.
```suggestion
	Jira *Jira `yaml:"jira,omitempty"`
```

2024-05-01 14:11 UTC, jonathanlam commented on pkg/models/tickets.go
> +	Jira    Jira `yaml:"jira,omitempty"`
we don't open separate github issues for every finding (above the severity threshold). it's only just the dashboards. the behaviour atm is if Jira is not installed/specified, a github issue will be created for each finding (on top of the dashboards). Since it just loops through newFindings and calls CreateTicket(finding).

Also what happens if they put Jira in the global config file but want to disable ticket creation on certain repos (e.g. don't create tickets for my internal tool python script that is only run locally).

2024-05-01 14:15 UTC, jonathanlam commented on examples/nullify.yaml
> +ticket_creation:
we can probably do a separate ticket_creation and project_platform. the former is for configuring what tickets are created, what threshold. the latter for setting up ticket platform specific data

project_platform might cause confusion between the git platform (version control) and their ticket platform. what do you think?

2024-05-02 04:11 UTC, jonathanlam commented on pkg/models/tickets.go
> +	Jira    Jira `yaml:"jira,omitempty"`
integrations:
  jira:
    disabled: true
    project_key:
    issue_type:
    threshold:

2024-05-02 07:08 UTC, tim-thacker-nullify approved these changes

2024-05-02 07:09 UTC, merged