Feat/jira assignee
Nullify-Platform/config-file-parser pull request #111
Opened 2024-05-09 02:10 UTC by jonathanlam

## Description

Add assignee to the Jira ticket.
You can specify either the userID or the person's display name.
You must only specify one or the other (or none if you don't want to assign anyone).
If you specify both, it will only assign it to the userID.
If there are multiple people with the same name, it will only assign it to the first person that matches. In the case of people with the same name, they should be using IDs. (they can add the name to the config file, but it won't be used. It will be more like a comment to assist the team remember who the ID belongs to).

## Checklist

- [ ] I have added one of the `patch`, `minor`, `major` or `no-release` labels
- [ ] I have linked an issue from this repository using the **Development** option
- [ ] I have performed a self-review of my own code
- [ ] I have checked for redundant or commented out code
- [ ] I have commented my code where I can't make it self-documenting
- [ ] I have made corresponding changes to the documentation
- [ ] I have added any appropriate tests

2024-05-09 12:45 UTC, tim-thacker-nullify requested changes

2024-05-09 12:45 UTC, tim-thacker-nullify commented on examples/nullify.yaml
> +      name: John Smith
can a user define either an id or a name?
can we provide either of these when assigning in jira issue in the jira API?

2024-05-09 23:31 UTC, jonathanlam commented on examples/nullify.yaml
> +      name: John Smith
https://github.com/Nullify-Platform/public-docs/pull/31

2024-05-10 05:47 UTC, tim-thacker-nullify approved these changes

2024-05-10 05:48 UTC, merged